### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marcjoyezama** [ccebinger/CTAN_Archivo#1]
Thanks for making the project. i got the error message "!pdfTeX error: pdflatex (file Archiv0-Bold.pfb): cannot open Type 1 font file for reading". What should be done?

**Comment by ccebinger** [comment]
I forgot to zip the "type1"-folder. Please try my latest upload to github: https://github.com/ccebinger/CTAN_Archivo/raw/master/Archivo.zip

I will do now a second upload to CTAN.

Best

**Comment by marcjoyezama** [comment]
Thx
